name: Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Get dependencies
        run: go mod download

      - name: Compile for Linux
        env:
          GOOS: linux
          GOARCH: amd64
        run: go build -v -o build/elden-ring-ersc-updater-linux-amd64

      - name: Compile for Windows
        env:
          GOOS: windows
          GOARCH: amd64
        run: go build -v -o build/elden-ring-ersc-updater-windows-amd64.exe

      - name: Compile for MacOS
        env:
          GOOS: darwin
          GOARCH: amd64
        run: go build -v -o build/elden-ring-ersc-updater-darwin-amd64

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: build/*