name: Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: 1.24

      - name: Check out code
        uses: actions/checkout@v5

      - name: Get dependencies
        run: go mod download

      - name: Run tests with coverage
        run: go test -race -coverprofile=coverage.txt -covermode=atomic ./...

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          files: ./coverage.txt
          fail_ci_if_error: false

  build-linux:
    name: Build for Linux
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: 1.24

      - name: Check out code
        uses: actions/checkout@v5

      - name: Get dependencies
        run: go mod download

      - name: Compile for Linux
        env:
          GOOS: linux
          GOARCH: amd64
        run: go build -v -o build/elden-ring-ersc-updater-linux-amd64

      - name: Upload Linux Artifact
        uses: actions/upload-artifact@v5
        with:
          name: linux-artifact
          path: build/elden-ring-ersc-updater-linux-amd64

  build-windows:
    name: Build for Windows
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: 1.24

      - name: Check out code
        uses: actions/checkout@v5

      - name: Get dependencies
        run: go mod download

      - name: Compile for Windows
        env:
          GOOS: windows
          GOARCH: amd64
        run: go build -v -o build/elden-ring-ersc-updater-windows-amd64.exe

      - name: Upload Windows Artifact
        uses: actions/upload-artifact@v5
        with:
          name: windows-artifact
          path: build/elden-ring-ersc-updater-windows-amd64.exe

  build-macos:
    name: Build for MacOS
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: 1.24

      - name: Check out code
        uses: actions/checkout@v5

      - name: Get dependencies
        run: go mod download

      - name: Compile for MacOS
        env:
          GOOS: darwin
          GOARCH: amd64
        run: go build -v -o build/elden-ring-ersc-updater-darwin-amd64

      - name: Upload MacOS Artifact
        uses: actions/upload-artifact@v5
        with:
          name: macos-artifact
          path: build/elden-ring-ersc-updater-darwin-amd64

  collect-artifacts:
    name: Collect All Artifacts
    runs-on: ubuntu-latest
    needs: [build-linux, build-windows, build-macos]
    steps:
      - name: Create build directory
        run: mkdir -p build

      - name: Download Linux Artifact
        uses: actions/download-artifact@v5
        with:
          name: linux-artifact
          path: build

      - name: Download Windows Artifact
        uses: actions/download-artifact@v5
        with:
          name: windows-artifact
          path: build

      - name: Download MacOS Artifact
        uses: actions/download-artifact@v5
        with:
          name: macos-artifact
          path: build

      - name: Upload All Artifacts
        uses: actions/upload-artifact@v5
        with:
          name: build-artifacts
          path: build/*
